image: gitpod/workspace-base

tasks:
- name: wget files
  init: |
    mkdir -p /workspace/test_files
    cd /workspace/test_files
    wget https://github.com/bcgsc/Canadian_Biogenome_Project/raw/V2/example_input/subset_covid_hifi.bam
    cd ..
- name: install mamba
  command: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
