image: gitpod/workspace-full-vnc

tasks:
- name: wget files
  init: |
    mkdir -p /workspace/nextflow-genomics/test_files
    cd /workspace/nextflow-genomics/test_files
    wget https://github.com/bcgsc/Canadian_Biogenome_Project/raw/V2/example_input/subset_covid_hifi.bam
    cd ..

- name: install mamba
  command: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc

    mamba create --mkdir --yes --quiet  bioconda::hifiasm=0.18.5 -n hifiasm
    

- name: Install Nextflow
  # https://www.nextflow.io/docs/latest/getstarted.html
  init: |
    cd /workspace/nextflow-genomics/      
    wget -qO- https://get.nextflow.io | bash
    chmod +x nextflow
    nextflow self-update

- name: Alias Nextflow
  init: |
    cd /workspace/nextflow-genomics/
    echo "alias nextflow_cmd='/workspace/nextflow-genomics/nextflow'" >> ~/.bashrc
    source ~/.bashrc

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
